"""update tables

Revision ID: eb710dc7ba80
Revises: 
Create Date: 2025-03-20 05:42:11.810987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb710dc7ba80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caption', sa.Column('url', sa.String(), nullable=False))
    op.drop_constraint('caption_media_id_fkey', 'caption', type_='foreignkey')
    op.drop_column('caption', 'media_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caption', sa.Column('media_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('caption_media_id_fkey', 'caption', 'media', ['media_id'], ['media_id'])
    op.drop_column('caption', 'url')
    # ### end Alembic commands ###
